### ISSUE TITLE
Can't start server, Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by slhck** [badlogic/heissepreise#60]
I just did a pull and now I can't start the server anymore:

```
➜ node index.js
undefined:1
�
^

SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.readJSON (/Users/werner/Documents/Software/heissepreise/analysis.js:20:17)
    at /Users/werner/Documents/Software/heissepreise/index.js:49:35
    at Object.<anonymous> (/Users/werner/Documents/Software/heissepreise/index.js:80:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

This is my content in `data`:

```
➜ ll data/                           
total 971104
-rw-r--r--  1 werner  staff   12505515 Jun  2 17:29 billa-2023-05-30.json.gz
-rw-r--r--  1 werner  staff   12503074 Jun  2 17:29 billa-2023-06-02.json.gz
-rw-r--r--  1 werner  staff    3367252 Jun  2 17:29 dm-2023-05-30.json.gz
-rw-r--r--  1 werner  staff    3397462 Jun  2 17:29 dm-2023-06-02.json.gz
-rw-r--r--  1 werner  staff    3456070 Jun  2 17:29 dmDe-2023-05-30.json.gz
-rw-r--r--  1 werner  staff    3465108 Jun  2 17:29 dmDe-2023-06-02.json.gz
-rw-r--r--  1 werner  staff     360676 Jun  2 17:29 hofer-2023-05-30.json.gz
-rw-r--r--  1 werner  staff     372567 Jun  2 17:29 hofer-2023-06-02.json.gz
-rw-r--r--  1 werner  staff   38604224 Jun  2 13:56 latest-canonical.json
-rw-r--r--  1 werner  staff     174390 Jun  2 17:29 lidl-2023-05-30.json.gz
-rw-r--r--  1 werner  staff     213130 Jun  2 17:29 lidl-2023-06-02.json.gz
-rw-r--r--  1 werner  staff   20171402 Jun  2 17:29 mpreis-2023-05-30.json.gz
-rw-r--r--  1 werner  staff  228688054 Jun  2 13:55 mpreis-2023-06-02.json
-rw-r--r--  1 werner  staff     678068 Jun  2 13:55 penny-2023-06-02.json
-rw-r--r--  1 werner  staff    3766875 Jun  2 13:55 reweDe-2023-06-02.json
-rw-r--r--  1 werner  staff   82036386 May 30 20:38 spar-2023-05-30.json
-rw-r--r--  1 werner  staff   82417204 Jun  2 13:55 spar-2023-06-02.json
-rw-r--r--  1 werner  staff     494554 May 30 20:38 unimarkt-2023-05-30.json
-rw-r--r--  1 werner  staff     494048 Jun  2 13:55 unimarkt-2023-06-02.json
```

I assume this is because of the recent changes wrt compression? Did something require migration?

My previous local commit for running the server was f21ac58.

Node v18.16.0 on macOS 13.

**Comment by iantsch** [comment]
oh you have a mixed state of data 😱

**Comment by iantsch** [comment]
[tools.zip](https://github.com/badlogic/heissepreise/files/11636959/tools.zip)

some tools for a manual conversion

json => gz
`node gzipJson.js data/`

gz => json
`node gunzipJson.js data/`

**Comment by slhck** [comment]
If it's just a problem between some commits, I don't care and can just reset. So no need to do complex migrations in-code.

**Comment by badlogic** [comment]
Alrighty, I've just pushed fixes. Please return `node index.js`. If that still fails, then I'm afraid you'll have to reset.

@iantsch I masacered your code baby :(

**Comment by slhck** [comment]
Almost!

It somehow gzips existing data twice:

```
➜ node index.js 3008
Migrating old .json data to .json.gz
data/billa-2023-05-30.json.gz -> data/billa-2023-05-30.json.gz.gz
data/billa-2023-06-02.json.gz -> data/billa-2023-06-02.json.gz.gz
data/dm-2023-05-30.json.gz -> data/dm-2023-05-30.json.gz.gz
data/dm-2023-06-02.json.gz -> data/dm-2023-06-02.json.gz.gz
data/dmDe-2023-05-30.json.gz -> data/dmDe-2023-05-30.json.gz.gz
data/dmDe-2023-06-02.json.gz -> data/dmDe-2023-06-02.json.gz.gz
data/hofer-2023-05-30.json.gz -> data/hofer-2023-05-30.json.gz.gz
data/hofer-2023-06-02.json.gz -> data/hofer-2023-06-02.json.gz.gz
data/lidl-2023-05-30.json.gz -> data/lidl-2023-05-30.json.gz.gz
data/lidl-2023-06-02.json.gz -> data/lidl-2023-06-02.json.gz.gz
data/mpreis-2023-05-30.json.gz -> data/mpreis-2023-05-30.json.gz.gz
data/mpreis-2023-06-02.json -> data/mpreis-2023-06-02.json.gz
data/penny-2023-06-02.json -> data/penny-2023-06-02.json.gz
data/reweDe-2023-06-02.json -> data/reweDe-2023-06-02.json.gz
```

Maybe you need to add something like:

```js
for(const file of files) {
  // skip if already gzipped
  if (file.indexOf(".gz") != -1) continue;
  // ...      
```

in the migrate loop?
